
#include "tracks.h"

#define RIGHT_TRACK_MOVE 11
#define RIGHT_TRACK_DIR 7
#define LEFT_TRACK_DIR 10
#define LEFT_TRACK_MOVE 5
#define LEFT_TRACK_PWM_CHANNEL 5
#define RIGHT_TRACK_PWM_CHANNEL 0
#define MOVEMENT_SPEED 70

uint8_t left_go_flag =0;
uint8_t right_go_flag =0;
uint8_t forward_go_flag =0;
uint8_t backward_go_flag =0;

void tracks_init(void){

	SIM->SCGC5 |= SIM_SCGC5_PORTB_MASK; 
	SIM->SCGC5 |= SIM_SCGC5_PORTA_MASK;
	SIM->SCGC6 |= SIM_SCGC6_TPM0_MASK;	
	SIM->SOPT2 |= SIM_SOPT2_TPMSRC(1); 
	
	PORTA -> PCR[LEFT_TRACK_MOVE]	|= PORT_PCR_MUX(2); 	//PTA5 as output PWM (TPM0_CH5)
	PORTB->PCR[RIGHT_TRACK_DIR] |= PORT_PCR_MUX(1);  		//GPIO PTB7 
	PORTB->PCR[LEFT_TRACK_DIR] |= PORT_PCR_MUX(1);			//GPIO PTB10
	PORTB->PCR[RIGHT_TRACK_MOVE] |= PORT_PCR_MUX(2);  	//PTB11 as output PWM (TPM0_CH0)
	
	PTA->PDDR |= (1<<LEFT_TRACK_MOVE); /* Set as óutput */
	PTB->PDDR |= (1<<RIGHT_TRACK_MOVE); 
	PTB->PDDR |= (1<<LEFT_TRACK_DIR); 
	PTB->PDDR |= (1<<RIGHT_TRACK_DIR);
	
	TPM0->SC |= TPM_SC_PS(3);  					
	TPM0->SC |= TPM_SC_CMOD(1);					
	TPM0->MOD = 100;
	TPM0->CONTROLS[RIGHT_TRACK_PWM_CHANNEL].CnSC |= (TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK);
	TPM0->CONTROLS[LEFT_TRACK_PWM_CHANNEL].CnSC |= (TPM_CnSC_MSB_MASK | TPM_CnSC_ELSA_MASK);
	TPM0->CONTROLS[RIGHT_TRACK_PWM_CHANNEL].CnV = 100; 
	TPM0->CONTROLS[LEFT_TRACK_PWM_CHANNEL].CnV = 100;		
	PTB->PDOR|=(0<<RIGHT_TRACK_DIR);
	PTB->PDOR|=(0<<LEFT_TRACK_DIR);
	
}

void go_left(void){
	PTB->PCOR|=(1 <<RIGHT_TRACK_DIR);	
	PTB->PSOR|=(1 <<LEFT_TRACK_DIR);
	TPM0->CONTROLS[RIGHT_TRACK_PWM_CHANNEL].CnV = MOVEMENT_SPEED;
	TPM0->CONTROLS[LEFT_TRACK_PWM_CHANNEL].CnV = MOVEMENT_SPEED;		
	left_go_flag = 1;
}

void go_right(void){
	PTB->PSOR|=(1 <<RIGHT_TRACK_DIR);	
	PTB->PCOR|=(1 <<LEFT_TRACK_DIR);
	TPM0->CONTROLS[RIGHT_TRACK_PWM_CHANNEL].CnV = MOVEMENT_SPEED; 
	TPM0->CONTROLS[LEFT_TRACK_PWM_CHANNEL].CnV = MOVEMENT_SPEED;
	right_go_flag = 1;
}
void go_forward(void){
	PTB->PCOR|=(1 <<RIGHT_TRACK_DIR);	
	PTB->PCOR|=(1 <<LEFT_TRACK_DIR);
	TPM0->CONTROLS[RIGHT_TRACK_PWM_CHANNEL].CnV = MOVEMENT_SPEED; 
	TPM0->CONTROLS[LEFT_TRACK_PWM_CHANNEL].CnV = MOVEMENT_SPEED;	
	forward_go_flag = 1;
}
void go_backward(void){
	PTB->PSOR|=(1 <<RIGHT_TRACK_DIR);	
	PTB->PSOR|=(1 <<LEFT_TRACK_DIR);
	TPM0->CONTROLS[RIGHT_TRACK_PWM_CHANNEL].CnV = MOVEMENT_SPEED; 
	TPM0->CONTROLS[LEFT_TRACK_PWM_CHANNEL].CnV = MOVEMENT_SPEED;	
	backward_go_flag = 1;
}

